### ISSUE TITLE
Contribution: QuackShot (test)

### ISSUE THREAD

**Issue by philipguin** [philipguin/JpdbGameDecks#1]
Request to begin creating a deck for QuackShot based on [this transcript](http://www.lltvg.com/wiki/Quackshot_Starring_Donald_Duck/Transcript) hosted on LLTVG. Should take approximate 30 minutes to an hour. Result should be high quality and very well sorted.

**Comment by philipguin** [comment]
Deck completed with the following info and files. Please add it to the list!

```yaml
name: QuackShot
store-link:
deck-author: Frizzil
difficulty: 2-3
difficulty-source: gpt4o
progress: complete
sortedness: 10
quality: 10
notes-and-sources: >-
  Based on an amazing
  <a href="http://www.lltvg.com/wiki/Quackshot_Starring_Donald_Duck/Transcript">transcript</a>
  from LLTVG!
  Thanks to the English annotations, I was able to accurately splice everything together for a <i>perfect</i> sort.
  We also have a kanji-injected version (kudos to gpt4o), since the original seemingly had none.
```

[QuackShot.csv](https://github.com/user-attachments/files/16488886/QuackShot.csv)
[QuackShot (Kanji-fied).csv](https://github.com/user-attachments/files/16488890/QuackShot.Kanji-fied.csv)
